import 'package:flutter/material.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookinguserwidget/generated/GeneratedGroup7336Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookinguserwidget/generated/GeneratedRectangle56Widget1.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookinguserwidget/generated/GeneratedGroup105Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookinguserwidget/generated/GeneratedBOOKINGWidget11.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookinguserwidget/generated/GeneratedSelectDateWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookinguserwidget/generated/GeneratedCAGE1Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookinguserwidget/generated/GeneratedGroup108Widget1.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookinguserwidget/generated/GeneratedGroup104Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookinguserwidget/generated/GeneratedChooseTimeWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookinguserwidget/generated/GeneratedCalenderWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookinguserwidget/generated/GeneratedGroup107Widget.dart';

/* Frame Facility Booking User
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFacilityBookingUserWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedCAGE1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 136.0,
                child: GeneratedRectangle56Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 195.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 17.0,
                child: GeneratedSelectDateWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 17.0,
                child: GeneratedChooseTimeWidget(),
              ),
              Positioned(
                left: 54.0,
                top: 491.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 39.0,
                child: GeneratedGroup104Widget(),
              ),
              Positioned(
                left: 186.0,
                top: 491.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 39.0,
                child: GeneratedGroup105Widget(),
              ),
              Positioned(
                left: 54.0,
                top: 535.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 39.0,
                child: GeneratedGroup108Widget1(),
              ),
              Positioned(
                left: 187.0,
                top: 535.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 39.0,
                child: GeneratedGroup107Widget(),
              ),
              Positioned(
                left: 112.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 32.0,
                child: GeneratedBOOKINGWidget11(),
              ),
              Positioned(
                left: 15.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 27.0,
                child: GeneratedGroup7336Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 219.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 224.0,
                child: GeneratedCalenderWidget(),
              )
            ]),
      ),
    ));
  }
}
