import 'package:flutter/material.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhelpuserwidget/generated/GeneratedPopularBlogWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhelpuserwidget/generated/GeneratedHelpWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhelpuserwidget/generated/GeneratedGroup7337Widget1.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhelpuserwidget/generated/GeneratedReadMoreWidget4.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhelpuserwidget/generated/GeneratedReadMoreWidget5.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhelpuserwidget/generated/GeneratedReadMoreWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhelpuserwidget/generated/GeneratedGroup7513Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhelpuserwidget/generated/GeneratedGroup7512Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhelpuserwidget/generated/GeneratedAskaQuestionWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhelpuserwidget/generated/GeneratedHowcanwehelpyouWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhelpuserwidget/generated/GeneratedGroup7510Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhelpuserwidget/generated/GeneratedGroup7515Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhelpuserwidget/generated/GeneratedGroup7511Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhelpuserwidget/generated/GeneratediconsearchWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhelpuserwidget/generated/GeneratedGroup7514Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhelpuserwidget/generated/GeneratedPopularArticlesWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhelpuserwidget/generated/GeneratedReadMoreWidget3.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhelpuserwidget/generated/GeneratedReadMoreWidget1.dart';

/* Frame Help User
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHelpUserWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 52.0,
                child: GeneratedHelpWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 40.0,
                child: GeneratedAskaQuestionWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 75.0,
                right: null,
                bottom: null,
                width: 214.0,
                height: 24.0,
                child: GeneratedHowcanwehelpyouWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.05555555555555555;

                  final double height = constraints.maxHeight * 0.03125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8333333333333334,
                        y: constraints.maxHeight * 0.1796875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconsearchWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 11.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 33.0,
                child: GeneratedGroup7337Widget1(),
              ),
              Positioned(
                left: 8.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 24.0,
                child: GeneratedPopularArticlesWidget(),
              ),
              Positioned(
                left: 8.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 24.0,
                child: GeneratedPopularBlogWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 205.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 70.0,
                child: GeneratedGroup7510Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 12.0,
                child: GeneratedReadMoreWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 70.0,
                child: GeneratedGroup7511Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 333.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 12.0,
                child: GeneratedReadMoreWidget1(),
              ),
              Positioned(
                left: 14.0,
                top: 373.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 70.0,
                child: GeneratedGroup7512Widget(),
              ),
              Positioned(
                left: 14.0,
                top: 373.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 70.0,
                child: GeneratedGroup7513Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 417.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 12.0,
                child: GeneratedReadMoreWidget3(),
              ),
              Positioned(
                left: 10.0,
                top: 481.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 70.0,
                child: GeneratedGroup7514Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 525.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 12.0,
                child: GeneratedReadMoreWidget4(),
              ),
              Positioned(
                left: 10.0,
                top: 565.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 70.0,
                child: GeneratedGroup7515Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 609.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 12.0,
                child: GeneratedReadMoreWidget5(),
              )
            ]),
      ),
    ));
  }
}
