import 'package:flutter/material.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser2widget/generated/GeneratedCourtWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser2widget/generated/GeneratedSeeAllWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser2widget/generated/GeneratedIconSeeAllWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser2widget/generated/GeneratedShowerWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser2widget/generated/GeneratedStoreCatalogWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser2widget/generated/GeneratedBookingNavbarWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser2widget/generated/GeneratedCAGEFacilitiesWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser2widget/generated/GeneratedAccountNavbarWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser2widget/generated/GeneratedHomeNavbarWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser2widget/generated/GeneratedGroup7334Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser2widget/generated/GeneratedGroup7495Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser2widget/generated/GeneratedGroup7496Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser2widget/generated/GeneratedGroup7494Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser2widget/generated/GeneratedRectangle18Widget7.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser2widget/generated/GeneratedParkingParkWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser2widget/generated/GeneratedGroup7497Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser2widget/generated/GeneratedNotifivationNavbarWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser2widget/generated/GeneratedGroup7511Widget1.dart';

/* Frame Home Page User 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomePageUser2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 46.0,
                child: GeneratedGroup7511Widget1(),
              ),
              Positioned(
                left: 13.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 27.0,
                child: GeneratedGroup7334Widget(),
              ),
              Positioned(
                left: 9.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 22.0,
                child: GeneratedStoreCatalogWidget(),
              ),
              Positioned(
                left: 262.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 18.0,
                child: GeneratedSeeAllWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 83.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 132.0,
                child: GeneratedGroup7494Widget(),
              ),
              Positioned(
                left: 190.0,
                top: 425.0,
                right: null,
                bottom: null,
                width: 132.54638671875,
                height: 122.0,
                child: GeneratedShowerWidget(),
              ),
              Positioned(
                left: 8.0,
                top: 219.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 22.0,
                child: GeneratedCAGEFacilitiesWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 162.0,
                child: GeneratedCourtWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 425.0,
                right: null,
                bottom: null,
                width: 134.54638671875,
                height: 122.0,
                child: GeneratedParkingParkWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 65.0,
                child: GeneratedRectangle18Widget7(),
              ),
              Positioned(
                left: 32.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 46.0,
                child: GeneratedHomeNavbarWidget(),
              ),
              Positioned(
                left: 94.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 52.0,
                child: GeneratedBookingNavbarWidget(),
              ),
              Positioned(
                left: 170.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 49.0,
                child: GeneratedNotifivationNavbarWidget(),
              ),
              Positioned(
                left: 272.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 51.0,
                child: GeneratedAccountNavbarWidget(),
              ),
              Positioned(
                left: 78.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 85.08235168457031,
                height: 113.0,
                child: GeneratedGroup7495Widget(),
              ),
              Positioned(
                left: 168.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 85.08235168457031,
                height: 113.0,
                child: GeneratedGroup7496Widget(),
              ),
              Positioned(
                left: 258.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 85.08235168457031,
                height: 113.0,
                child: GeneratedGroup7497Widget(),
              ),
              Positioned(
                left: 331.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedIconSeeAllWidget(),
              )
            ]),
      ),
    ));
  }
}
