import 'package:flutter/material.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser1widget/generated/GeneratedGroup7307Widget1.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser1widget/generated/GeneratedEventWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser1widget/generated/GeneratedBOOKINGWidget5.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser1widget/generated/GeneratedEllipse5Widget2.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser1widget/generated/GeneratedCAGECUPWidget1.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser1widget/generated/GeneratedChooseaneventWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser1widget/generated/GeneratedAbasketballtournamentheldbyCAGEARENAtodevelopplayerstal.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser1widget/generated/GeneratedLogoWidget2.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser1widget/generated/GeneratedGroup7311Widget1.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser1widget/generated/GeneratedHelloPlayerWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser1widget/generated/GeneratedRectangle18Widget2.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser1widget/generated/GeneratedEllipse6Widget2.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser1widget/generated/GeneratedIconBackWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser1widget/generated/GeneratedGroup7312Widget1.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser1widget/generated/GeneratedRectangle17Widget1.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser1widget/generated/GeneratedGroup7313Widget1.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser1widget/generated/GeneratedAreYouReadyForTheEventWidget.dart';

/* Frame Event User 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEventUser1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 52.0,
                child: GeneratedEventWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 27.0,
                child: GeneratedIconBackWidget(),
              ),
              Positioned(
                left: 9.0,
                top: 75.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 22.0,
                child: GeneratedHelloPlayerWidget(),
              ),
              Positioned(
                left: 13.0,
                top: 95.0,
                right: null,
                bottom: null,
                width: 202.0,
                height: 12.0,
                child: GeneratedAreYouReadyForTheEventWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 127.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 12.0,
                child: GeneratedChooseaneventWidget(),
              ),
              Positioned(
                left: 60.0,
                top: 158.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 312.0,
                child: GeneratedRectangle17Widget1(),
              ),
              Positioned(
                left: 189.8914337158203,
                top: 419.2530517578125,
                right: null,
                bottom: null,
                width: 95.03014373779297,
                height: 31.951807022094727,
                child: GeneratedBOOKINGWidget5(),
              ),
              Positioned(
                left: 75.55047607421875,
                top: 175.85546875,
                right: null,
                bottom: null,
                width: 71.34883117675781,
                height: 29.14453125,
                child: GeneratedLogoWidget2(),
              ),
              Positioned(
                left: 80.99992370605469,
                top: 346.0,
                right: null,
                bottom: null,
                width: 83.41085815429688,
                height: 20.795181274414062,
                child: GeneratedCAGECUPWidget1(),
              ),
              Positioned(
                left: 42.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 14.558823585510254,
                height: 12.0,
                child: GeneratedEllipse5Widget2(),
              ),
              Positioned(
                left: 66.26470947265625,
                top: 502.0,
                right: null,
                bottom: null,
                width: 14.558823585510254,
                height: 12.0,
                child: GeneratedEllipse6Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 65.0,
                child: GeneratedRectangle18Widget2(),
              ),
              Positioned(
                left: 32.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 46.0,
                child: GeneratedGroup7307Widget1(),
              ),
              Positioned(
                left: 94.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 52.0,
                child: GeneratedGroup7311Widget1(),
              ),
              Positioned(
                left: 170.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 49.0,
                child: GeneratedGroup7312Widget1(),
              ),
              Positioned(
                left: 269.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 51.0,
                child: GeneratedGroup7313Widget1(),
              ),
              Positioned(
                left: 90.0,
                top: 366.0,
                right: null,
                bottom: null,
                width: 192.0,
                height: 36.0,
                child:
                    GeneratedAbasketballtournamentheldbyCAGEARENAtodevelopplayerstal(),
              )
            ]),
      ),
    ));
  }
}
