import 'package:flutter/material.dart';
import 'package:flutterapp/cage_20arenaapp/generatedloginpageuserwidget/generated/GeneratedRectangle4201Widget.dart';

/* Frame Login Page User
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginPageUserWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 75.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 210.0,
                height: 90.0,
                child: GeneratedRectangle4201Widget(),
              )
            ]),
      ),
    ));
  }
}
