import 'package:flutter/material.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookingusermemberwidget/generated/GeneratedEllipse8Widget2.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookingusermemberwidget/generated/GeneratedEllipse6Widget3.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookingusermemberwidget/generated/GeneratedACCOUNTWidget4.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookingusermemberwidget/generated/GeneratedNOTIFICATIONWidget4.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookingusermemberwidget/generated/GeneratedCAGE1Widget1.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookingusermemberwidget/generated/GeneratedCage1Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookingusermemberwidget/generated/GeneratedFacilityBookingWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookingusermemberwidget/generated/GeneratedGroup7490Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookingusermemberwidget/generated/GeneratedRectangle18Widget3.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookingusermemberwidget/generated/GeneratedEllipse9Widget2.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookingusermemberwidget/generated/GeneratedEllipse7Widget2.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookingusermemberwidget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookingusermemberwidget/generated/GeneratedBOOKINGWidget15.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookingusermemberwidget/generated/GeneratedThenumberonearenareadyforyoutorentandplayWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookingusermemberwidget/generated/GeneratedHOMEWidget5.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookingusermemberwidget/generated/GeneratedGroup93Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedfacilitybookingusermemberwidget/generated/GeneratedEllipse5Widget3.dart';

/* Frame Facility Booking User Member
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFacilityBookingUserMemberWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 52.0,
                child: GeneratedFacilityBookingWidget(),
              ),
              Positioned(
                left: 113.0,
                top: 510.0,
                right: null,
                bottom: null,
                width: 16.434782028198242,
                height: 17.0,
                child: GeneratedEllipse5Widget3(),
              ),
              Positioned(
                left: 140.3912353515625,
                top: 510.0,
                right: null,
                bottom: null,
                width: 16.434782028198242,
                height: 17.0,
                child: GeneratedEllipse6Widget3(),
              ),
              Positioned(
                left: 167.78274536132812,
                top: 510.0,
                right: null,
                bottom: null,
                width: 16.434782028198242,
                height: 17.0,
                child: GeneratedEllipse7Widget2(),
              ),
              Positioned(
                left: 195.17398071289062,
                top: 510.0,
                right: null,
                bottom: null,
                width: 16.434782028198242,
                height: 17.0,
                child: GeneratedEllipse8Widget2(),
              ),
              Positioned(
                left: 222.56521606445312,
                top: 510.0,
                right: null,
                bottom: null,
                width: 16.434782028198242,
                height: 17.0,
                child: GeneratedEllipse9Widget2(),
              ),
              Positioned(
                left: 47.0,
                top: 158.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 332.0,
                child: GeneratedCage1Widget(),
              ),
              Positioned(
                left: 189.0,
                top: 436.0,
                right: null,
                bottom: null,
                width: 103.88888549804688,
                height: 34.0,
                child: GeneratedGroup93Widget(),
              ),
              Positioned(
                left: 64.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 77.99999237060547,
                height: 33.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 25.0,
                child: GeneratedCAGE1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 65.0,
                child: GeneratedRectangle18Widget3(),
              ),
              Positioned(
                left: 36.0,
                top: 585.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 46.0,
                child: GeneratedHOMEWidget5(),
              ),
              Positioned(
                left: 107.0,
                top: 585.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 52.0,
                child: GeneratedBOOKINGWidget15(),
              ),
              Positioned(
                left: 184.0,
                top: 585.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 49.0,
                child: GeneratedNOTIFICATIONWidget4(),
              ),
              Positioned(
                left: 287.0,
                top: 583.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 51.0,
                child: GeneratedACCOUNTWidget4(),
              ),
              Positioned(
                left: 23.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 50.0,
                child: GeneratedGroup7490Widget(),
              ),
              Positioned(
                left: 80.0,
                top: 384.0,
                right: null,
                bottom: null,
                width: 209.0,
                height: 28.0,
                child:
                    GeneratedThenumberonearenareadyforyoutorentandplayWidget(),
              )
            ]),
      ),
    ));
  }
}
