import 'package:flutter/material.dart';
import 'package:flutterapp/cage_20arenaapp/generatednotificationuserwidget/generated/GeneratedGroup7502Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatednotificationuserwidget/generated/GeneratedRectangle18Widget5.dart';
import 'package:flutterapp/cage_20arenaapp/generatednotificationuserwidget/generated/GeneratedReadMoreWidget8.dart';
import 'package:flutterapp/cage_20arenaapp/generatednotificationuserwidget/generated/GeneratedBookingWidget1.dart';
import 'package:flutterapp/cage_20arenaapp/generatednotificationuserwidget/generated/GeneratedNotificationWidget1.dart';
import 'package:flutterapp/cage_20arenaapp/generatednotificationuserwidget/generated/GeneratedReadMoreWidget10.dart';
import 'package:flutterapp/cage_20arenaapp/generatednotificationuserwidget/generated/GeneratedGroup7503Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatednotificationuserwidget/generated/GeneratedHomeWidget2.dart';
import 'package:flutterapp/cage_20arenaapp/generatednotificationuserwidget/generated/GeneratedNoticationWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatednotificationuserwidget/generated/GeneratedGroup7500Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatednotificationuserwidget/generated/GeneratedReadMoreWidget11.dart';
import 'package:flutterapp/cage_20arenaapp/generatednotificationuserwidget/generated/GeneratedGroup7498Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatednotificationuserwidget/generated/GeneratedReadMoreWidget6.dart';
import 'package:flutterapp/cage_20arenaapp/generatednotificationuserwidget/generated/GeneratedGroup7501Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatednotificationuserwidget/generated/GeneratedIconBackWidget2.dart';
import 'package:flutterapp/cage_20arenaapp/generatednotificationuserwidget/generated/GeneratedAccountWidget1.dart';
import 'package:flutterapp/cage_20arenaapp/generatednotificationuserwidget/generated/GeneratedReadMoreWidget7.dart';
import 'package:flutterapp/cage_20arenaapp/generatednotificationuserwidget/generated/GeneratedGroup7499Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatednotificationuserwidget/generated/GeneratedReadMoreWidget9.dart';

/* Frame Notification User
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNotificationUserWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 46.0,
                child: GeneratedNoticationWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 27.0,
                child: GeneratedIconBackWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 65.0,
                child: GeneratedRectangle18Widget5(),
              ),
              Positioned(
                left: 32.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 46.0,
                child: GeneratedHomeWidget2(),
              ),
              Positioned(
                left: 94.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 52.0,
                child: GeneratedBookingWidget1(),
              ),
              Positioned(
                left: 170.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 49.0,
                child: GeneratedNotificationWidget1(),
              ),
              Positioned(
                left: 272.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 51.0,
                child: GeneratedAccountWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 70.0,
                child: GeneratedGroup7498Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 70.0,
                child: GeneratedGroup7499Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 70.0,
                child: GeneratedGroup7500Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 70.0,
                child: GeneratedGroup7501Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 396.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 70.0,
                child: GeneratedGroup7502Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 70.0,
                child: GeneratedGroup7503Widget(),
              ),
              Positioned(
                left: 250.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 12.0,
                child: GeneratedReadMoreWidget6(),
              ),
              Positioned(
                left: 250.0,
                top: 209.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 12.0,
                child: GeneratedReadMoreWidget7(),
              ),
              Positioned(
                left: 250.0,
                top: 288.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 12.0,
                child: GeneratedReadMoreWidget8(),
              ),
              Positioned(
                left: 250.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 12.0,
                child: GeneratedReadMoreWidget9(),
              ),
              Positioned(
                left: 250.0,
                top: 446.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 12.0,
                child: GeneratedReadMoreWidget10(),
              ),
              Positioned(
                left: 250.0,
                top: 525.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 12.0,
                child: GeneratedReadMoreWidget11(),
              )
            ]),
      ),
    ));
  }
}
