import 'package:flutter/material.dart';
import 'package:flutterapp/cage_20arenaapp/generatedregisterpageuserwidget/generated/GeneratedMaleWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedregisterpageuserwidget/generated/GeneratedFemaleWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedregisterpageuserwidget/generated/GeneratedLine23Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedregisterpageuserwidget/generated/GeneratedGroup7504Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedregisterpageuserwidget/generated/GeneratedFullNameWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedregisterpageuserwidget/generated/GeneratedAtaumanualWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedregisterpageuserwidget/generated/GeneratedLine24Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedregisterpageuserwidget/generated/GeneratedPhoneNumberWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedregisterpageuserwidget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedregisterpageuserwidget/generated/GeneratedBirthDateWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedregisterpageuserwidget/generated/GeneratedRegisterWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedregisterpageuserwidget/generated/GeneratedAddressWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedregisterpageuserwidget/generated/GeneratedWelcomeWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedregisterpageuserwidget/generated/GeneratedLoginwithgoogleWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedregisterpageuserwidget/generated/GeneratedLogoWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedregisterpageuserwidget/generated/GeneratedEmailWidget.dart';

/* Frame Register Page User
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegisterPageUserWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 129.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 70.0,
                child: GeneratedLogoWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 30.0,
                child: GeneratedWelcomeWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 13.0,
                child: GeneratedGroup7504Widget(),
              ),
              Positioned(
                left: 110.0,
                top: 546.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 34.0,
                child: GeneratedRegisterWidget(),
              ),
              Positioned(
                left: 63.0,
                top: 262.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 20.0,
                child: GeneratedFullNameWidget(),
              ),
              Positioned(
                left: 63.0,
                top: 302.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 20.0,
                child: GeneratedEmailWidget(),
              ),
              Positioned(
                left: 63.0,
                top: 342.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 20.0,
                child: GeneratedPhoneNumberWidget(),
              ),
              Positioned(
                left: 63.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 20.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 63.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 20.0,
                child: GeneratedBirthDateWidget(),
              ),
              Positioned(
                left: 63.0,
                top: 462.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 20.0,
                child: GeneratedAddressWidget(),
              ),
              Positioned(
                left: 63.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 14.0,
                child: GeneratedMaleWidget(),
              ),
              Positioned(
                left: 172.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 14.0,
                child: GeneratedFemaleWidget(),
              ),
              Positioned(
                left: 138.0,
                top: 197.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 17.0,
                child: GeneratedAtaumanualWidget(),
              ),
              Positioned(
                left: 102.0,
                top: 205.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 1.0,
                child: GeneratedLine23Widget(),
              ),
              Positioned(
                left: 220.0,
                top: 205.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 1.0,
                child: GeneratedLine24Widget(),
              ),
              Positioned(
                left: 95.0,
                top: 167.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 30.0,
                child: GeneratedLoginwithgoogleWidget(),
              )
            ]),
      ),
    ));
  }
}
