import 'package:flutter/material.dart';
import 'package:flutterapp/cage_20arenaapp/generatedstorecataloguserwidget/generated/GeneratedLogoWidget3.dart';
import 'package:flutterapp/cage_20arenaapp/generatedstorecataloguserwidget/generated/GeneratedEllipse5Widget4.dart';
import 'package:flutterapp/cage_20arenaapp/generatedstorecataloguserwidget/generated/GeneratedEllipse6Widget4.dart';
import 'package:flutterapp/cage_20arenaapp/generatedstorecataloguserwidget/generated/GeneratedGroup7347Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedstorecataloguserwidget/generated/GeneratedEllipse8Widget3.dart';
import 'package:flutterapp/cage_20arenaapp/generatedstorecataloguserwidget/generated/GeneratedGroup129Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/cage_20arenaapp/generatedstorecataloguserwidget/generated/GeneratedEllipse9Widget3.dart';
import 'package:flutterapp/cage_20arenaapp/generatedstorecataloguserwidget/generated/GeneratedBuyWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedstorecataloguserwidget/generated/GeneratedEllipse7Widget3.dart';
import 'package:flutterapp/cage_20arenaapp/generatedstorecataloguserwidget/generated/GeneratedRelatedProductsWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedstorecataloguserwidget/generated/GeneratedThedortmundbvbjerseywhichissuitableformakingmyoutfitmor.dart';
import 'package:flutterapp/cage_20arenaapp/generatedstorecataloguserwidget/generated/Generated150KWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedstorecataloguserwidget/generated/GeneratedGroup76Widget8.dart';
import 'package:flutterapp/cage_20arenaapp/generatedstorecataloguserwidget/generated/GeneratedGroup7346Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedstorecataloguserwidget/generated/GeneratediconsearchWidget2.dart';
import 'package:flutterapp/cage_20arenaapp/generatedstorecataloguserwidget/generated/GeneratedGroup132Widget1.dart';
import 'package:flutterapp/cage_20arenaapp/generatedstorecataloguserwidget/generated/GeneratedJersey3x3Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedstorecataloguserwidget/generated/GeneratedGroup7348Widget.dart';

/* Frame Store Catalog User
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStoreCatalogUserWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 60.0,
                top: 106.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 312.0,
                child: GeneratedGroup76Widget8(),
              ),
              Positioned(
                left: 189.8914337158203,
                top: 367.2530517578125,
                right: null,
                bottom: null,
                width: 95.03014373779297,
                height: 31.951807022094727,
                child: GeneratedBuyWidget(),
              ),
              Positioned(
                left: 75.55047607421875,
                top: 123.85546875,
                right: null,
                bottom: null,
                width: 71.34883117675781,
                height: 28.14453125,
                child: GeneratedLogoWidget3(),
              ),
              Positioned(
                left: 80.99992370605469,
                top: 294.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 21.0,
                child: GeneratedJersey3x3Widget(),
              ),
              Positioned(
                left: 203.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 28.0,
                child: Generated150KWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 453.0,
                right: null,
                bottom: null,
                width: 16.434782028198242,
                height: 17.0,
                child: GeneratedEllipse5Widget4(),
              ),
              Positioned(
                left: 53.391231536865234,
                top: 453.0,
                right: null,
                bottom: null,
                width: 16.434782028198242,
                height: 17.0,
                child: GeneratedEllipse6Widget4(),
              ),
              Positioned(
                left: 80.78274536132812,
                top: 453.0,
                right: null,
                bottom: null,
                width: 16.434782028198242,
                height: 17.0,
                child: GeneratedEllipse7Widget3(),
              ),
              Positioned(
                left: 108.1739730834961,
                top: 453.0,
                right: null,
                bottom: null,
                width: 16.434782028198242,
                height: 17.0,
                child: GeneratedEllipse8Widget3(),
              ),
              Positioned(
                left: 135.56521606445312,
                top: 453.0,
                right: null,
                bottom: null,
                width: 16.434782028198242,
                height: 17.0,
                child: GeneratedEllipse9Widget3(),
              ),
              Positioned(
                left: 10.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 22.0,
                child: GeneratedRelatedProductsWidget(),
              ),
              Positioned(
                left: 336.0,
                top: 519.0,
                right: null,
                bottom: null,
                width: 85.08235168457031,
                height: 113.0,
                child: GeneratedGroup132Widget1(),
              ),
              Positioned(
                left: 98.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 41.0,
                child:
                    GeneratedThedortmundbvbjerseywhichissuitableformakingmyoutfitmor(),
              ),
              Positioned(
                left: 27.0,
                top: 517.0,
                right: null,
                bottom: null,
                width: 85.08235168457031,
                height: 113.0,
                child: GeneratedGroup7346Widget(),
              ),
              Positioned(
                left: 130.0,
                top: 517.0,
                right: null,
                bottom: null,
                width: 85.08235168457031,
                height: 113.0,
                child: GeneratedGroup7347Widget(),
              ),
              Positioned(
                left: 233.0,
                top: 518.0,
                right: null,
                bottom: null,
                width: 85.08235168457031,
                height: 113.0,
                child: GeneratedGroup7348Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 40.0,
                child: GeneratedGroup129Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.05555555555555555;

                  final double height = constraints.maxHeight * 0.03125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8111111111111111,
                        y: constraints.maxHeight * 0.046875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconsearchWidget2(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
