import 'package:flutter/material.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser2widget/generated/GeneratedCODWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser2widget/generated/GeneratedEmailWidget2.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser2widget/generated/GeneratedTeamNameWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser2widget/generated/GeneratedRegisterWidget1.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser2widget/generated/GeneratedCAGECUPWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser2widget/generated/GeneratedGroup110Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser2widget/generated/GeneratedDANAWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser2widget/generated/GeneratedOVOWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser2widget/generated/GeneratedGroup108Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser2widget/generated/GeneratedPaymentMethodWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser2widget/generated/GeneratedComingSoonWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser2widget/generated/GeneratedRegistrationFeeWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser2widget/generated/GeneratedBCAWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedeventuser2widget/generated/GeneratedAreYouReadyForTheEvent3X33Okt10OktWidget.dart';

/* Frame Event User 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEventUser2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 150.0,
                child: GeneratedGroup108Widget(),
              ),
              Positioned(
                left: 6.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 83.41085815429688,
                height: 20.795181274414062,
                child: GeneratedCAGECUPWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 184.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 32.0,
                child: GeneratedAreYouReadyForTheEvent3X33Okt10OktWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 24.317644119262695,
                child: GeneratedComingSoonWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 65.0,
                child: GeneratedEmailWidget2(),
              ),
              Positioned(
                left: 15.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 65.0,
                child: GeneratedTeamNameWidget(),
              ),
              Positioned(
                left: 7.0,
                top: 385.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 17.0,
                child: GeneratedRegistrationFeeWidget(),
              ),
              Positioned(
                left: 8.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 19.0,
                child: GeneratedPaymentMethodWidget(),
              ),
              Positioned(
                left: 11.0,
                top: 411.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 34.0,
                child: GeneratedGroup110Widget(),
              ),
              Positioned(
                left: 8.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 34.0,
                child: GeneratedCODWidget(),
              ),
              Positioned(
                left: 96.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 34.0,
                child: GeneratedOVOWidget(),
              ),
              Positioned(
                left: 183.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 34.0,
                child: GeneratedDANAWidget(),
              ),
              Positioned(
                left: 271.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 34.0,
                child: GeneratedBCAWidget(),
              ),
              Positioned(
                left: 109.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 32.0,
                child: GeneratedRegisterWidget1(),
              )
            ]),
      ),
    ));
  }
}
