import 'package:flutter/material.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaboutususerwidget/generated/GeneratedHISTORYWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaboutususerwidget/generated/GeneratedAboutUsWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaboutususerwidget/generated/GeneratedWhatsthatCAGEARENAWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaboutususerwidget/generated/GeneratedGroup7339Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaboutususerwidget/generated/GeneratedWhyBecauseCAGEARENAwasformedtodevelopthetalentofplayers.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaboutususerwidget/generated/GeneratediconsearchWidget1.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaboutususerwidget/generated/GeneratedGroup7516Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaboutususerwidget/generated/GeneratedGroup7Widget1.dart';

/* Frame About Us User
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAboutUsUserWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 52.0,
                child: GeneratedAboutUsWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 43.20000076293945,
                child: GeneratedGroup7Widget1(),
              ),
              Positioned(
                left: -1.0,
                top: 198.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 43.0,
                child: GeneratedWhatsthatCAGEARENAWidget(),
              ),
              Positioned(
                left: -4.0,
                top: 255.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 25.0,
                child: GeneratedHISTORYWidget(),
              ),
              Positioned(
                left: 13.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 33.0,
                child: GeneratedGroup7339Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 322.0,
                child:
                    GeneratedWhyBecauseCAGEARENAwasformedtodevelopthetalentofplayers(),
              ),
              Positioned(
                left: 15.0,
                top: 131.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 40.0,
                child: GeneratedGroup7516Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.05555555555555555;

                  final double height = constraints.maxHeight * 0.03125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8055555555555556,
                        y: constraints.maxHeight * 0.2203125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconsearchWidget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
