import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/cage_20arenaapp/generatedloginpageuserwidget2/generated/GeneratedIconhideandseeWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedloginpageuserwidget2/generated/GeneratedPasswordWidget2.dart';
import 'package:flutterapp/cage_20arenaapp/generatedloginpageuserwidget2/generated/GeneratedBelumpunyaakunDaftardisiniWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedloginpageuserwidget2/generated/GeneratedLOGINWidget1.dart';
import 'package:flutterapp/cage_20arenaapp/generatedloginpageuserwidget2/generated/GeneratedGUESTWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedloginpageuserwidget2/generated/GeneratedLOGINWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedloginpageuserwidget2/generated/GeneratedUsernameWidget3.dart';
import 'package:flutterapp/cage_20arenaapp/generatedloginpageuserwidget2/generated/GeneratedLoginwithGoogleWidget1.dart';
import 'package:flutterapp/cage_20arenaapp/generatedloginpageuserwidget2/generated/GeneratedLoginWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedloginpageuserwidget2/generated/GeneratedLupapasswordWidget.dart';

/* Frame Login Page User
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginPageUserWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 124.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 36.0,
                child: GeneratedLoginWidget(),
              ),
              Positioned(
                left: 102.0,
                top: 393.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 23.0,
                child: GeneratedLOGINWidget(),
              ),
              Positioned(
                left: 101.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 23.0,
                child: GeneratedGUESTWidget(),
              ),
              Positioned(
                left: 93.0,
                top: 459.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 22.0,
                child: GeneratedBelumpunyaakunDaftardisiniWidget(),
              ),
              Positioned(
                left: 92.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 28.571428298950195,
                child: GeneratedLoginwithGoogleWidget1(),
              ),
              Positioned(
                left: 160.0,
                top: 397.6190490722656,
                right: null,
                bottom: null,
                width: 47.0,
                height: 17.380952835083008,
                child: GeneratedLOGINWidget1(),
              ),
              Positioned(
                left: 44.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 39.0,
                child: GeneratedUsernameWidget3(),
              ),
              Positioned(
                left: 235.0,
                top: 376.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 12.0,
                child: GeneratedLupapasswordWidget(),
              ),
              Positioned(
                left: 44.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 39.0,
                child: GeneratedPasswordWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.041666666666666664;

                  final double height = constraints.maxHeight * 0.0234375;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7777777777777778,
                        y: constraints.maxHeight * 0.546875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedIconhideandseeWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
