import 'package:flutter/material.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedActivateMemberUserWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedGroup76Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedContinueWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedGetDocumentationWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedGetmorepromosandattractiveprizesbybecomingaCAGEMemberAR.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedMemberBenefitWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedBOOKINGWidget1.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedContinueWidget4.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedACCOUNTWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedGroup119Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedGroup114Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedGroup7337Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedGetRewardWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedHOMEWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedContinueWidget2.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedSUBSCRIBENOWWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedGetPromoWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedMemberPackageWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedHemat150Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedGroup115Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedactivatememberuserwidget/generated/GeneratedNOTIFICATIONWidget.dart';

/* Frame Activate Member user
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedActivateMemberuserWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 52.0,
                child: GeneratedActivateMemberUserWidget(),
              ),
              Positioned(
                left: -1.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 51.0,
                child: GeneratedGroup76Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 17.0,
                child: GeneratedMemberPackageWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 170.0,
                child: GeneratedGroup114Widget(),
              ),
              Positioned(
                left: 157.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 170.0,
                child: GeneratedGroup115Widget(),
              ),
              Positioned(
                left: 303.0,
                top: 167.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 170.0,
                child: GeneratedGroup119Widget(),
              ),
              Positioned(
                left: 63.0,
                top: 442.0,
                right: null,
                bottom: null,
                width: 233.0,
                height: 38.0,
                child: GeneratedSUBSCRIBENOWWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 17.0,
                child: GeneratedMemberBenefitWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 30.0,
                child: GeneratedGetRewardWidget(),
              ),
              Positioned(
                left: 127.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 30.0,
                child: GeneratedGetPromoWidget(),
              ),
              Positioned(
                left: 240.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 159.0,
                height: 30.0,
                child: GeneratedGetDocumentationWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 27.0,
                child: GeneratedGroup7337Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 25.0,
                child: GeneratedContinueWidget(),
              ),
              Positioned(
                left: 177.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 25.0,
                child: GeneratedContinueWidget2(),
              ),
              Positioned(
                left: 321.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 25.0,
                child: GeneratedContinueWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 65.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 30.0833740234375,
                top: 582.0,
                right: null,
                bottom: null,
                width: 41.113887786865234,
                height: 46.0,
                child: GeneratedHOMEWidget(),
              ),
              Positioned(
                left: 94.2611083984375,
                top: 582.0,
                right: null,
                bottom: null,
                width: 55.15277862548828,
                height: 52.0,
                child: GeneratedBOOKINGWidget1(),
              ),
              Positioned(
                left: 170.47222900390625,
                top: 584.0,
                right: null,
                bottom: null,
                width: 81.2249984741211,
                height: 49.0,
                child: GeneratedNOTIFICATIONWidget(),
              ),
              Positioned(
                left: 272.75555419921875,
                top: 582.0,
                right: null,
                bottom: null,
                width: 67.18611145019531,
                height: 51.0,
                child: GeneratedACCOUNTWidget(),
              ),
              Positioned(
                left: 172.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 7.0,
                child: GeneratedHemat150Widget(),
              ),
              Positioned(
                left: 14.0,
                top: 356.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 62.0,
                child:
                    GeneratedGetmorepromosandattractiveprizesbybecomingaCAGEMemberAR(),
              )
            ]),
      ),
    ));
  }
}
