import 'package:flutter/material.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser1widget/generated/GeneratedRectangle18Widget1.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser1widget/generated/Generated12Oktober2022Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser1widget/generated/GeneratedGroup22Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser1widget/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser1widget/generated/GeneratedGroup21Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser1widget/generated/GeneratedHomeWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser1widget/generated/GeneratedGroup7313Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser1widget/generated/GeneratedTopPromoWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser1widget/generated/GeneratedWednesdayWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser1widget/generated/GeneratedTopCourtWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser1widget/generated/GeneratedGroup7312Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser1widget/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser1widget/generated/GeneratedGroup7307Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser1widget/generated/GeneratedGoodMorningAgathaWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser1widget/generated/GeneratedGroup7311Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser1widget/generated/GeneratedGroup27Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedhomepageuser1widget/generated/GeneratedRectangle44Widget.dart';

/* Frame Home Page User 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomePageUser1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 46.0,
                child: GeneratedHomeWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedGroup18Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 130.0,
                child: GeneratedGroup20Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 6.0,
                child: GeneratedGroup21Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 6.0,
                child: GeneratedGroup27Widget(),
              ),
              Positioned(
                left: 5.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 22.0,
                child: GeneratedGroup22Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 50.0,
                child: GeneratedRectangle44Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 12.0,
                child: GeneratedGoodMorningAgathaWidget(),
              ),
              Positioned(
                left: 250.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 15.0,
                child: GeneratedWednesdayWidget(),
              ),
              Positioned(
                left: 237.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 13.0,
                child: Generated12Oktober2022Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 65.0,
                child: GeneratedRectangle18Widget1(),
              ),
              Positioned(
                left: 30.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 46.0,
                child: GeneratedGroup7307Widget(),
              ),
              Positioned(
                left: 94.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 52.0,
                child: GeneratedGroup7311Widget(),
              ),
              Positioned(
                left: 170.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 49.0,
                child: GeneratedGroup7312Widget(),
              ),
              Positioned(
                left: 272.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 51.0,
                child: GeneratedGroup7313Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 385.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 170.0,
                child: GeneratedTopPromoWidget(),
              ),
              Positioned(
                left: 186.0,
                top: 385.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 170.0,
                child: GeneratedTopCourtWidget(),
              )
            ]),
      ),
    ));
  }
}
