import 'package:flutter/material.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaccountuserwidget/generated/GeneratedGroup7335Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaccountuserwidget/generated/GeneratedRectangle18Widget6.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaccountuserwidget/generated/GeneratedRectangle38Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaccountuserwidget/generated/GeneratedRectangle39Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaccountuserwidget/generated/GeneratedAccountWidget2.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaccountuserwidget/generated/GeneratedGroup7313Widget2.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaccountuserwidget/generated/GeneratedMemberWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaccountuserwidget/generated/GeneratedProfileWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaccountuserwidget/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaccountuserwidget/generated/GeneratedGroup7311Widget2.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaccountuserwidget/generated/GeneratedRectangle37Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaccountuserwidget/generated/GeneratedRectangle40Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaccountuserwidget/generated/GeneratedRectangle41Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaccountuserwidget/generated/GeneratedNewPostWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaccountuserwidget/generated/GeneratedUserNameWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaccountuserwidget/generated/GeneratedGroup7312Widget2.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaccountuserwidget/generated/GeneratedPHOTOSWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaccountuserwidget/generated/GeneratedRectangle36Widget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaccountuserwidget/generated/GeneratedEditProfileWidget.dart';
import 'package:flutterapp/cage_20arenaapp/generatedaccountuserwidget/generated/GeneratedGroup7307Widget2.dart';

/* Frame Account User
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAccountUserWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 46.0,
                child: GeneratedAccountWidget2(),
              ),
              Positioned(
                left: 15.0,
                top: 106.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 93.0,
                child: GeneratedProfileWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 30.0,
                child: GeneratedEditProfileWidget(),
              ),
              Positioned(
                left: 123.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 196.0,
                height: 52.0,
                child: GeneratedRectangle34Widget(),
              ),
              Positioned(
                left: 123.0,
                top: 122.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 18.0,
                child: GeneratedUserNameWidget(),
              ),
              Positioned(
                left: 13.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 20.0,
                child: GeneratedPHOTOSWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 94.0,
                child: GeneratedRectangle36Widget(),
              ),
              Positioned(
                left: 124.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 94.0,
                child: GeneratedRectangle37Widget(),
              ),
              Positioned(
                left: 231.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 94.0,
                child: GeneratedRectangle38Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 518.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 94.0,
                child: GeneratedNewPostWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 94.0,
                child: GeneratedRectangle39Widget(),
              ),
              Positioned(
                left: 124.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 94.0,
                child: GeneratedRectangle40Widget(),
              ),
              Positioned(
                left: 230.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 94.0,
                child: GeneratedRectangle41Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 65.0,
                child: GeneratedRectangle18Widget6(),
              ),
              Positioned(
                left: 32.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 46.0,
                child: GeneratedGroup7307Widget2(),
              ),
              Positioned(
                left: 94.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 52.0,
                child: GeneratedGroup7311Widget2(),
              ),
              Positioned(
                left: 170.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 49.0,
                child: GeneratedGroup7312Widget2(),
              ),
              Positioned(
                left: 272.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 51.0,
                child: GeneratedGroup7313Widget2(),
              ),
              Positioned(
                left: 13.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 27.0,
                child: GeneratedGroup7335Widget(),
              ),
              Positioned(
                left: 230.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 34.0,
                child: GeneratedMemberWidget(),
              )
            ]),
      ),
    ));
  }
}
